# Generated by Django 5.1.6 on 2026-09-14 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='slug')),
                ('valor', models.PositiveSmallIntegerField(default=0, verbose_name='valor')),
                ('categoria', models.CharField(choices=[('NEGOCIO', 'Negocio'), ('TECNICA', 'Tecnica'), ('PERSONAL', 'Personal'), ('SALUD', 'Salud')], default='NEGOCIO', max_length=20, verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'atributo',
                'verbose_name_plural': 'atributos',
                'ordering': ['categoria', '-valor'],
                'indexes': [models.Index(fields=['slug'], name='attribute_slug_idx'), models.Index(fields=['categoria'], name='attribute_categoria_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre')),
                ('orden', models.PositiveSmallIntegerField(unique=True, verbose_name='orden')),
                ('nivel_min', models.PositiveSmallIntegerField(verbose_name='nivel minimo')),
                ('nivel_max', models.PositiveSmallIntegerField(verbose_name='nivel maximo')),
                ('objetivo', models.TextField(blank=True, verbose_name='objetivo')),
                ('criterio_ascenso', models.TextField(blank=True, verbose_name='criterio de ascenso')),
                ('jefe', models.CharField(blank=True, max_length=120, verbose_name='jefe de rango')),
            ],
            options={
                'verbose_name': 'rango',
                'verbose_name_plural': 'rangos',
                'ordering': ['orden'],
                'indexes': [models.Index(fields=['orden'], name='rank_orden_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField(default=45, verbose_name='nivel')),
                ('xp_total', models.IntegerField(default=0, verbose_name='XP total')),
                ('fecha_inicio', models.DateField(auto_now_add=True, verbose_name='fecha de inicio')),
                ('altura_cm', models.PositiveSmallIntegerField(default=175, verbose_name='altura (cm)')),
                ('peso_objetivo', models.DecimalField(decimal_places=2, default=77, max_digits=5, verbose_name='peso objetivo (kg)')),
                ('rango', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='core.rank', verbose_name='rango')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='AttributeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('valor', models.PositiveSmallIntegerField(verbose_name='valor')),
                ('nota', models.TextField(blank=True, verbose_name='nota')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.attribute', verbose_name='atributo')),
            ],
            options={
                'verbose_name': 'registro de atributo',
                'verbose_name_plural': 'registros de atributos',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='attrlog_fecha_idx'), models.Index(fields=['attribute', '-fecha'], name='attrlog_attr_fecha_idx')],
            },
        ),
    ]
