# Generated by Django 5.1.6 on 2026-09-14 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de inicio'),
        ),
    ]
