# Generated by Django 5.1.6 on 2026-09-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rangos'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='evidencia',
            field=models.TextField(blank=True, help_text='Por que el atributo vale lo que vale, con hechos.', verbose_name='evidencia'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='siguiente_hito',
            field=models.TextField(blank=True, help_text='Lo concreto que hay que hacer para subirlo diez puntos.', verbose_name='que mueve el siguiente +10'),
        ),
    ]
