# Generated by Django 5.1.6 on 2026-09-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hoja_de_personaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='categoria',
            field=models.CharField(choices=[('NEGOCIO', 'Negocio'), ('TECNICA', 'Técnica'), ('PERSONAL', 'Personal'), ('SALUD', 'Salud')], default='NEGOCIO', max_length=20, verbose_name='categoria'),
        ),
    ]
