# Generated by Django 5.1.6 on 2026-09-14 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maxim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, verbose_name='numero')),
                ('libro', models.CharField(blank=True, max_length=80, verbose_name='libro')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('principio', models.TextField(blank=True, verbose_name='principio')),
                ('texto', models.TextField(verbose_name='texto')),
                ('aplicacion', models.TextField(blank=True, verbose_name='aplicacion concreta')),
                ('tags', models.CharField(blank=True, help_text='Separadas por comas.', max_length=200, verbose_name='etiquetas')),
            ],
            options={
                'verbose_name': 'maxima',
                'verbose_name_plural': 'maximas',
                'ordering': ['numero'],
                'indexes': [models.Index(fields=['numero'], name='maxim_numero_idx'), models.Index(fields=['libro'], name='maxim_libro_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='slug')),
                ('nombre', models.CharField(max_length=160, verbose_name='nombre')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='version')),
            ],
            options={
                'verbose_name': 'prompt de sistema',
                'verbose_name_plural': 'prompts de sistema',
                'ordering': ['slug', '-version'],
                'indexes': [models.Index(fields=['slug'], name='systemprompt_slug_idx'), models.Index(fields=['activo'], name='systemprompt_activo_idx')],
                'constraints': [models.UniqueConstraint(fields=('slug', 'version'), name='systemprompt_slug_version_unicos')],
            },
        ),
        migrations.CreateModel(
            name='AdviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('pregunta', models.TextField(verbose_name='pregunta')),
                ('contexto_json', models.JSONField(blank=True, default=dict, verbose_name='contexto')),
                ('respuesta', models.TextField(blank=True, verbose_name='respuesta')),
                ('modelo', models.CharField(blank=True, max_length=80, verbose_name='modelo')),
                ('tokens_in', models.PositiveIntegerField(default=0, verbose_name='tokens de entrada')),
                ('tokens_out', models.PositiveIntegerField(default=0, verbose_name='tokens de salida')),
                ('coste_estimado', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='coste estimado (EUR)')),
                ('system_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones', to='wisdom.systemprompt', verbose_name='prompt usado')),
            ],
            options={
                'verbose_name': 'consulta al consejo',
                'verbose_name_plural': 'consultas al consejo',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='advice_fecha_idx'), models.Index(fields=['modelo', '-fecha'], name='advice_modelo_idx')],
            },
        ),
    ]
