# Generated by Django 5.1.6 on 2026-09-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisdom', '0004_prompt_consejo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprompt',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='slug'),
        ),
    ]
