# Generated by Django 5.1.6 on 2026-09-14 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='fecha')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='peso (kg)')),
                ('cintura', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='cintura (cm)')),
                ('sueno_horas', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='horas de sueno')),
                ('energia', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='energia (1-5)')),
                ('entreno', models.BooleanField(default=False, verbose_name='entreno')),
                ('tipo_entreno', models.CharField(blank=True, max_length=80, verbose_name='tipo de entreno')),
            ],
            options={
                'verbose_name': 'registro de salud',
                'verbose_name_plural': 'registros de salud',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='healthlog_fecha_idx'), models.Index(fields=['entreno', '-fecha'], name='healthlog_entreno_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='anio')),
                ('semana_iso', models.PositiveSmallIntegerField(verbose_name='semana ISO')),
                ('fecha', models.DateField(verbose_name='fecha de la revision')),
                ('m1_eur_cobrados', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='1 · EUR cobrados (mes)')),
                ('m2_eur_recurrentes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='2 · EUR recurrentes activos/mes')),
                ('m3_eur_vencidos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='3 · EUR vencidos sin cobrar')),
                ('m4_contactos_nuevos', models.PositiveSmallIntegerField(default=0, verbose_name='4 · contactos nuevos')),
                ('m5_conversaciones', models.PositiveSmallIntegerField(default=0, verbose_name='5 · conversaciones')),
                ('m5_propuestas', models.PositiveSmallIntegerField(default=0, verbose_name='5 · propuestas')),
                ('m6_precio_medio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='6 · precio medio propuesto')),
                ('m7_tarifa_efectiva', models.DecimalField(decimal_places=2, default=0, help_text='Metrica maestra: EUR del mes / horas del mes.', max_digits=8, verbose_name='7 · tarifa efectiva (EUR/h)')),
                ('m8_revision_hecha', models.BooleanField(default=False, verbose_name='8 · revision hecha')),
                ('m8_wip_abierto', models.PositiveSmallIntegerField(default=0, verbose_name='8 · WIP abierto')),
                ('m9_entrenos', models.PositiveSmallIntegerField(default=0, verbose_name='9 · entrenos (0-4)')),
                ('m9_peso_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='9 · peso medio (kg)')),
                ('m10_bloques_intactos', models.BooleanField(default=True, verbose_name='10 · bloques con Alexandra intactos')),
                ('xp_semana', models.IntegerField(default=0, verbose_name='XP de la semana')),
                ('funciono', models.TextField(blank=True, verbose_name='funciono')),
                ('no_funciono', models.TextField(blank=True, verbose_name='no funciono')),
                ('decision', models.TextField(blank=True, verbose_name='una decision para la semana que viene')),
                ('objetivo_1', models.CharField(blank=True, max_length=255, verbose_name='objetivo 1')),
                ('objetivo_2', models.CharField(blank=True, max_length=255, verbose_name='objetivo 2')),
                ('objetivo_3', models.CharField(blank=True, max_length=255, verbose_name='objetivo 3')),
            ],
            options={
                'verbose_name': 'revision semanal',
                'verbose_name_plural': 'revisiones semanales',
                'ordering': ['-anio', '-semana_iso'],
                'indexes': [models.Index(fields=['-anio', '-semana_iso'], name='weeklyreview_semana_idx'), models.Index(fields=['-fecha'], name='weeklyreview_fecha_idx')],
                'constraints': [models.UniqueConstraint(fields=('anio', 'semana_iso'), name='weeklyreview_unica_por_semana')],
            },
        ),
    ]
