# Generated by Django 5.1.6 on 2026-09-14 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='titulo')),
                ('tipo', models.CharField(choices=[('DIARIA', 'Diaria'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual'), ('ANUAL', 'Anual'), ('PRINCIPAL', 'Principal')], db_index=True, max_length=12, verbose_name='tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion')),
                ('definicion_terminada', models.CharField(help_text='Que tiene que ser cierto para darla por hecha.', max_length=255, verbose_name='definicion de terminada')),
                ('tiempo_estimado_min', models.PositiveSmallIntegerField(default=0, verbose_name='tiempo estimado (min)')),
                ('xp', models.IntegerField(default=0, verbose_name='XP')),
                ('motivo', models.TextField(blank=True, verbose_name='por que')),
                ('evidencia_requerida', models.BooleanField(default=False, verbose_name='requiere evidencia')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('es_minima', models.BooleanField(default=False, help_text='Version reducida que mantiene la racha en un dia malo.', verbose_name='es version minima')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misiones', to='core.attribute', verbose_name='atributo que mueve')),
            ],
            options={
                'verbose_name': 'mision',
                'verbose_name_plural': 'misiones',
                'ordering': ['tipo', 'orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='MissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('completada', models.BooleanField(default=False, verbose_name='completada')),
                ('evidencia_texto', models.TextField(blank=True, verbose_name='evidencia')),
                ('evidencia_url', models.URLField(blank=True, verbose_name='enlace de evidencia')),
                ('xp_otorgado', models.IntegerField(default=0, verbose_name='XP otorgada')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='missions.mission', verbose_name='mision')),
            ],
            options={
                'verbose_name': 'registro de mision',
                'verbose_name_plural': 'registros de misiones',
                'ordering': ['-fecha', 'mission__orden'],
            },
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['tipo', 'activa'], name='mission_tipo_activa_idx'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['activa', 'orden'], name='mission_activa_orden_idx'),
        ),
        migrations.AddIndex(
            model_name='missionlog',
            index=models.Index(fields=['-fecha'], name='missionlog_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='missionlog',
            index=models.Index(fields=['fecha', 'completada'], name='missionlog_fecha_comp_idx'),
        ),
        migrations.AddIndex(
            model_name='missionlog',
            index=models.Index(fields=['mission', '-fecha'], name='missionlog_mis_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='missionlog',
            constraint=models.UniqueConstraint(fields=('mission', 'fecha'), name='missionlog_unica_por_dia'),
        ),
    ]
