# Generated by Django 5.1.6 on 2026-09-14 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rangos'),
        ('missions', '0002_misiones_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='rango_max',
            field=models.ForeignKey(blank=True, help_text='Vacio = no se retira nunca.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misiones_hasta', to='core.rank', verbose_name='disponible hasta el rango'),
        ),
        migrations.AddField(
            model_name='mission',
            name='rango_min',
            field=models.ForeignKey(blank=True, help_text='Vacio = disponible desde el principio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misiones_desde', to='core.rank', verbose_name='disponible desde el rango'),
        ),
    ]
