# Generated by Django 5.1.6 on 2026-09-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_misiones_por_rango'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='etiqueta_notas',
            field=models.CharField(blank=True, help_text="Rotulo del cuaderno, p. ej. 'Las dos tareas de manana'.", max_length=120, verbose_name='que se apunta'),
        ),
        migrations.AddField(
            model_name='mission',
            name='pide_notas',
            field=models.BooleanField(default=False, help_text='Al completarla se abre un cuaderno para apuntar. Es el caso del cierre del dia: lo anotado ES la mision.', verbose_name='abre el cuaderno'),
        ),
    ]
