# Generated by Django 5.1.6 on 2026-09-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0009_arreglar_manana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='etiqueta_notas',
            field=models.CharField(blank=True, help_text="Rótulo del cuaderno, p. ej. 'Las dos tareas de mañana'.", max_length=120, verbose_name='que se apunta'),
        ),
    ]
