# Generated by Django 5.1.6 on 2026-09-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0010_rotulo_del_cuaderno'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='eleccion',
            field=models.SlugField(blank=True, help_text='Vacío = obligatoria. Con valor, entra en ese grupo de «elige una».', max_length=60, verbose_name='grupo de elección'),
        ),
        migrations.AddField(
            model_name='mission',
            name='regla_xp',
            field=models.SlugField(blank=True, help_text='Slug de una XPRule. Deja el tope semanal de esa regla en pie.', max_length=60, verbose_name='regla de XP'),
        ),
    ]
