# Generated by Django 5.1.6 on 2026-09-14 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('regla_slug', models.SlugField(max_length=60, verbose_name='slug de la regla')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('xp', models.IntegerField(help_text='Negativa.', verbose_name='XP')),
                ('correccion_exigida', models.TextField(verbose_name='correccion exigida')),
                ('resuelta', models.BooleanField(default=False, verbose_name='resuelta')),
            ],
            options={
                'verbose_name': 'penalizacion',
                'verbose_name_plural': 'penalizaciones',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='penalty_fecha_idx'), models.Index(fields=['resuelta', '-fecha'], name='penalty_resuelta_idx'), models.Index(fields=['regla_slug'], name='penalty_regla_idx')],
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('categoria', models.CharField(choices=[('RESULTADO', 'Resultado'), ('SOPORTE', 'Soporte'), ('CONSUMO', 'Consumo'), ('PENALIZACION', 'Penalizacion')], max_length=14, verbose_name='categoria')),
                ('accion_slug', models.SlugField(max_length=60, verbose_name='slug de la accion')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripcion')),
                ('xp_bruto', models.IntegerField(verbose_name='XP bruta')),
                ('xp_neto', models.IntegerField(verbose_name='XP neta')),
                ('tope_aplicado', models.BooleanField(default=False, verbose_name='tope aplicado')),
                ('multiplicador_racha', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='multiplicador de racha')),
                ('fuente', models.CharField(choices=[('MISION', 'Mision'), ('MANUAL', 'Manual'), ('AUTO', 'Automatica')], default='MANUAL', max_length=8, verbose_name='fuente')),
                ('objeto_relacionado', models.CharField(blank=True, help_text="Referencia libre, p. ej. 'invoice:12' o 'deal:4'.", max_length=120, verbose_name='objeto relacionado')),
            ],
            options={
                'verbose_name': 'evento de XP',
                'verbose_name_plural': 'eventos de XP',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['-fecha'], name='xpevent_fecha_idx'), models.Index(fields=['accion_slug', '-fecha'], name='xpevent_slug_fecha_idx'), models.Index(fields=['categoria', '-fecha'], name='xpevent_cat_fecha_idx')],
            },
        ),
        migrations.CreateModel(
            name='XPRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion_slug', models.SlugField(max_length=60, unique=True, verbose_name='slug de la accion')),
                ('nombre', models.CharField(max_length=160, verbose_name='nombre')),
                ('xp', models.IntegerField(verbose_name='XP')),
                ('tope_semanal', models.IntegerField(blank=True, help_text='Vacio = sin tope.', null=True, verbose_name='tope semanal')),
                ('categoria', models.CharField(choices=[('RESULTADO', 'Resultado'), ('SOPORTE', 'Soporte'), ('CONSUMO', 'Consumo'), ('PENALIZACION', 'Penalizacion')], default='RESULTADO', max_length=14, verbose_name='categoria')),
                ('activa', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'regla de XP',
                'verbose_name_plural': 'reglas de XP',
                'ordering': ['categoria', '-xp'],
                'indexes': [models.Index(fields=['accion_slug'], name='xprule_slug_idx'), models.Index(fields=['categoria', 'activa'], name='xprule_cat_activa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='titulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripcion')),
                ('nivel_requerido', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='nivel requerido')),
                ('desbloqueada', models.BooleanField(default=False, verbose_name='desbloqueada')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha de desbloqueo')),
                ('rango', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recompensas', to='core.rank', verbose_name='rango requerido')),
            ],
            options={
                'verbose_name': 'recompensa',
                'verbose_name_plural': 'recompensas',
                'ordering': ['nivel_requerido', 'titulo'],
                'indexes': [models.Index(fields=['desbloqueada'], name='reward_desbloqueada_idx'), models.Index(fields=['nivel_requerido'], name='reward_nivel_idx')],
            },
        ),
    ]
