# Generated by Django 5.1.6 on 2026-09-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0002_tabla_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(verbose_name='anio')),
                ('semana_iso', models.PositiveSmallIntegerField(verbose_name='semana ISO')),
                ('fecha_activacion', models.DateField(verbose_name='fecha de activacion')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo')),
            ],
            options={
                'verbose_name': 'semana de reinicio',
                'verbose_name_plural': 'semanas de reinicio',
                'ordering': ['-anio', '-semana_iso'],
                'indexes': [models.Index(fields=['-anio', '-semana_iso'], name='resetweek_semana_idx')],
                'constraints': [models.UniqueConstraint(fields=('anio', 'semana_iso'), name='resetweek_unica_por_semana')],
            },
        ),
    ]
