# Generated by Django 5.1.6 on 2026-09-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0003_resetweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='disfrutada',
            field=models.BooleanField(default=False, verbose_name='disfrutada'),
        ),
        migrations.AddField(
            model_name='reward',
            name='fecha_disfrute',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de disfrute'),
        ),
    ]
