# Generated by Django 5.1.6 on 2026-09-14 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, verbose_name='nombre')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='slug')),
                ('sector', models.CharField(blank=True, max_length=120, verbose_name='sector')),
                ('url', models.URLField(blank=True, verbose_name='web')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('POTENCIAL', 'Potencial'), ('PERDIDO', 'Perdido')], default='ACTIVO', max_length=10, verbose_name='estado')),
                ('mrr', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='recurrente (EUR/mes)')),
                ('fecha_alta', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de alta')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['slug'], name='client_slug_idx'), models.Index(fields=['estado'], name='client_estado_idx'), models.Index(fields=['sector'], name='client_sector_idx'), models.Index(fields=['-fecha_alta'], name='client_alta_idx')],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negocio', models.CharField(max_length=160, verbose_name='negocio')),
                ('contacto', models.CharField(blank=True, max_length=160, verbose_name='contacto')),
                ('canal', models.CharField(blank=True, help_text='Referido, gimnasio, frio, entrante...', max_length=120, verbose_name='canal')),
                ('sector', models.CharField(blank=True, max_length=120, verbose_name='sector')),
                ('estado', models.CharField(choices=[('CONTACTADO', 'Contactado'), ('CONVERSANDO', 'Conversando'), ('PROPUESTA', 'Propuesta enviada'), ('GANADO', 'Ganado'), ('PERDIDO', 'Perdido')], default='CONTACTADO', max_length=12, verbose_name='estado')),
                ('valor_potencial', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor potencial (EUR)')),
                ('fecha_primer_contacto', models.DateField(default=django.utils.timezone.localdate, verbose_name='primer contacto')),
                ('ultimo_toque', models.DateField(blank=True, null=True, verbose_name='ultimo toque')),
                ('proximo_paso', models.CharField(blank=True, max_length=255, verbose_name='proximo paso')),
                ('fecha_proximo_paso', models.DateField(blank=True, null=True, verbose_name='fecha del proximo paso')),
                ('motivo_perdida', models.TextField(blank=True, help_text="Un 'no' explicado vale mas que diez conversaciones agradables.", verbose_name='motivo de perdida')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='business.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'oportunidad',
                'verbose_name_plural': 'pipeline',
                'ordering': ['-fecha_primer_contacto'],
                'indexes': [models.Index(fields=['estado'], name='deal_estado_idx'), models.Index(fields=['-fecha_primer_contacto'], name='deal_primer_contacto_idx'), models.Index(fields=['ultimo_toque'], name='deal_ultimo_toque_idx'), models.Index(fields=['fecha_proximo_paso'], name='deal_prox_paso_idx'), models.Index(fields=['estado', 'ultimo_toque'], name='deal_estado_toque_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255, verbose_name='concepto')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='importe (EUR)')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de emision')),
                ('vencimiento', models.DateField(verbose_name='vencimiento')),
                ('cobrada', models.BooleanField(default=False, verbose_name='cobrada')),
                ('fecha_cobro', models.DateField(blank=True, null=True, verbose_name='fecha de cobro')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='business.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'ordering': ['-fecha_emision'],
                'indexes': [models.Index(fields=['cobrada'], name='invoice_cobrada_idx'), models.Index(fields=['vencimiento'], name='invoice_vencimiento_idx'), models.Index(fields=['-fecha_emision'], name='invoice_emision_idx'), models.Index(fields=['cobrada', 'vencimiento'], name='invoice_cobrada_venc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, verbose_name='nombre')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio (EUR)')),
                ('horas_estimadas', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='horas estimadas')),
                ('horas_reales', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='horas reales')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('ENTREGADO', 'Entregado'), ('CONGELADO', 'Congelado')], default='ACTIVO', max_length=10, verbose_name='estado')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de inicio')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='fecha de entrega')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='business.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['estado'], name='project_estado_idx'), models.Index(fields=['-fecha_inicio'], name='project_inicio_idx'), models.Index(fields=['fecha_entrega'], name='project_entrega_idx')],
            },
        ),
    ]
