# Generated by Django 5.1.6 on 2026-09-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='rechazado_por_precio',
            field=models.BooleanField(default=False, help_text='Lo rechazaste tu por estar por debajo del suelo. Son +150 XP.', verbose_name='rechazado por precio bajo'),
        ),
    ]
