# Generated by Django 5.1.6 on 2026-09-15 06:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=160, verbose_name='titulo')),
                ('contenido', models.TextField(verbose_name='contenido')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('fijada', models.BooleanField(default=False, help_text='Las fijadas se quedan arriba, fuera del orden por fecha.', verbose_name='fijada')),
                ('creada', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('actualizada', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ['-fecha', '-creada'],
                'indexes': [models.Index(fields=['-fecha'], name='note_fecha_idx'), models.Index(fields=['fijada', '-fecha'], name='note_fijada_fecha_idx')],
            },
        ),
    ]
